version: "1.0"

networks:
  plancton-net:

services:
  backend:
    container_name: backend-plancton
    image: backend-plancton:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    environment:
      - DATABASE_HOST=database-plancton
      - DATABASE_PORT=27017
      - DATABASE_NAME=plancton
      - DATABASE_USERNAME=planctonuser
      - DATABASE_PASSWORD=Zz486%0,&1>)
      - APP_PORT=3000
    networks:
      - plancton-net
    ports:
      - "8081:3000"

  database:
    container_name: database-plancton
    hostname: database-plancton
    image: mongo:latest
    restart: always
    networks:
      - plancton-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: planctonuser
      MONGO_INITDB_ROOT_PASSWORD: Zz486%0,&1>)
    volumes:
      - /plancton/database:/data/db